name: Publish Container Image to ECR

on:
  push:
    branches:
      - main

# OIDC permissions for keyless authentication
permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    name: Publish container image
    runs-on: ubuntu-latest

    steps:
      # get source code
      - name: Checkout resource code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # configure AWS credentials
      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to Amazon ECR
      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # build and push tagged image to Amazon ECR
      - name: Build and Push Image to ECR
        id: build-image
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          docker build \
            --build-arg VITE_API_KEY=$VITE_API_KEY \
            --build-arg VITE_BASE_URL=$VITE_BASE_URL \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
